### ISSUE TITLE
Control Morph Progress

### ISSUE THREAD

**Issue by DaniloTrotta** [VedantSG123/R3FPointsFX#4]
Hey, first of all this is a great package! Thank you for making this. 

I was wondering if its possible to control the transition progress between 2 models. I am planning to morph between 2 models depending on how far the user has scrolled. (Probably gonna usa GSAP Scroll triggers for this) 

Is this possible by using the vertexShader progress uniform or how would I achieve this?

**Comment by VedantSG123** [comment]
Hi thanks for considering my package. Sure you can morph the particles based on the progress of the scroll. Here is the code snippet, which I used in one of my projects.
```jsx
//particles transition timelines
//transition from mesh 0 to 1 and revert back on reverse scroll
  //first
  useEffect(() => {
    if (morphRef.current) {
      const ctx = GSAP.context(() => {
        const timeline1 = GSAP.timeline({
          scrollTrigger: {
            trigger: section1,
            scroller: "#main",
            start: "bottom bottom-=100px",
            end: "bottom top+=100px",
            scrub: 1,
            onUpdate: (self) => {
              morphRef.current.updateProgress(self.progress)
            },
            onEnter: () => {
              morphRef.current.setModelB(1)
            },
            onLeave: () => {
              morphRef.current.setModelA(1)
            },
            onEnterBack: () => {
              morphRef.current.setModelA(0)
            },
            onLeaveBack: () => {
              morphRef.current.setModelB(0)
            },
          },
        })
      })
      return () => ctx.revert()
    }
  }, [])
```

The numbers 0 and 1 are the respective indexes of the mesh array which you are passing. Make sure that if there is one more transition after this, you may give some gap in between the scroll trigger elements. Please let me know if you need any further help.

**Comment by DaniloTrotta** [comment]
Thanks this helped a lot! 

One last question. 

I added a new user defined uniform inside my vertex Shader function for the Mouse position.
I want to do some mouse interaction for the particles. 

The problem is that in the ref there is no way to access the user defined uniforms so I can't update the mousePos uniform. 
Any Ideas ?

**Comment by VedantSG123** [comment]
Hi Danilo
You can access your uniform using the `getPointsMesh()` method available in the ref of the component. Here is the example in this screenshot:-
![Screenshot 2024-02-26 202656](https://github.com/VedantSG123/R3FPointsFX/assets/103552663/b2687a2d-6f94-4ff7-afbe-f9d54f930a05)
