### ISSUE TITLE
Inquiry Regarding R3f Points FX Library

### ISSUE THREAD

**Issue by TimeLightCurve** [VedantSG123/R3FPointsFX#5]
I am reaching out to you as I have been exploring the capabilities of your library in my current project. While I have found it to be a remarkable tool, I have encountered a hurdle that I am hoping you might be able to assist me with.

Specifically, I am endeavoring to employ a scroll trigger (using GSAP) to seamlessly transition shapes from model A to model B as users navigate through different sections of my application. However, despite my efforts, I am encountering a challenge where the animation fails to display smoothly, and the model changes abruptly. Interestingly, when I utilize a button trigger, mirroring your provided example, everything functions flawlessly.

https://github.com/TimeLightCurve/Phylon

video :

https://streamable.com/ejc17t

as you can notice in the video if i scroll after animation duration ( which is 2 seconds ) and then scroll ( each section triggers to a new model) the animation wont work, but if i scroll to next section before that 2 seconds duration the animation works perfectly

[CodeSandBox ](https://codesandbox.io/p/github/TimeLightCurve/Phylon/main?file=%2Fsrc%2Fmain.tsx%3A11%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clto5lnyf0006356ia9at7rm3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clto5lnyf0002356ia404nv4x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clto5lnyf0004356i04orqqww%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clto5lnyf0005356iawg6izsf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clto5lnyf0002356ia404nv4x%2522%253A%257B%2522id%2522%253A%2522clto5lnyf0002356ia404nv4x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clto6als30002356ij7j5tk75%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clto6als30002356ij7j5tk75%2522%257D%252C%2522clto5lnyf0005356iawg6izsf%2522%253A%257B%2522id%2522%253A%2522clto5lnyf0005356iawg6izsf%2522%252C%2522activeTabId%2522%253A%2522clto5ob2x00py356iyiziklor%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clto5ob2x00py356iyiziklor%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clto5lnyf0004356i04orqqww%2522%253A%257B%2522id%2522%253A%2522clto5lnyf0004356i04orqqww%2522%252C%2522activeTabId%2522%253A%2522clto688af00ig356i407wdahh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clto5lnyf0003356iqta9wr3h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clto5lopw0010dgek8xgj2tc7%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clto5lox80051356ijybmg9ld%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clto5nii500e9356ivxizla5a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522GIT_LOG%2522%252C%2522shellId%2522%253A%2522clto6afqd001tdgek4jojdc0u%2522%252C%2522id%2522%253A%2522clto688af00ig356i407wdahh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by VedantSG123** [comment]
Hi @TimeLightCurve can you please specifically share the part of code where you are implementing GSAP scroll trigger to create particle transition?

**Comment by TimeLightCurve** [comment]
sure @VedantSG123  this is the code 
`
export const Interface = (props:properties) => {
    
    const { changeNumber} = props
    const sectionRef1 = useRef <HTMLDivElement>(null)
    const sectionRef2 = useRef <HTMLDivElement >(null)
    const sectionRef3 = useRef <HTMLDivElement>(null)

    const sections= [sectionRef1, sectionRef2, sectionRef3]


    function handleScroll(e: Event) {
        e.preventDefault();
    }
    const scrolling: Scrolling = {
        enabled: true,
        events: "scroll,wheel,touchmove,pointermove".split(","),
        prevent: (e: Event ) => e.preventDefault(),
        disable() {
        if (scrolling.enabled) {
            scrolling.enabled = false;
            window.addEventListener("scroll", gsap.ticker.tick, {passive: true});
            scrolling.events.forEach((e, i) => (i ? document : window).addEventListener(e, handleScroll, {passive: false}));
        }
        },
        enable() {
        if (!scrolling.enabled) {
            scrolling.enabled = true;
            window.removeEventListener("scroll", gsap.ticker.tick);
            scrolling.events.forEach((e, i) => (i ? document : window).removeEventListener(e, handleScroll));
        }
        }
    };

    function goToSection(section :any) {
        if (scrolling.enabled) { 
        scrolling.disable();
        gsap.to(window, {
            scrollTo: {y: section, autoKill: false},
            onComplete: scrolling.enable,
            duration: 1
        });
    } 
    }
    useLayoutEffect(() => {
        sections.forEach((section, i) => {
        ScrollTrigger.create({
            trigger: section.current,
            start: "top bottom-=1",
            end: "bottom top+=1",
            onEnter: () => {goToSection(section.current),changeNumber(i),console.log(i);
            },
            onEnterBack: () => {goToSection(section.current),changeNumber(i),console.log(i);
            }
        });
        })
    },[])  


    return(
        <div className='flex flex-col items-center '>

        <div ref={sectionRef1} className=' text-white w-screen h-screen mx-auto'>
          <section>
            <h1 className=' text-black'> hi first box</h1>
          </section>
        </div>
        <div ref={sectionRef2} className='   w-screen h-screen mx-auto'>
          <section>
            <h1>  second box</h1>
          </section>
        </div>
        <div ref={sectionRef3} className='  w-screen h-screen mx-auto'>
          <section>
            <h1>  third box</h1>
          </section>
        </div>

      </div>
    )
}`

**Comment by TimeLightCurve** [comment]
> sure @VedantSG123 this is the code ` export const Interface = (props:properties) => {
> 
> ```
> const { changeNumber} = props
> const sectionRef1 = useRef <HTMLDivElement>(null)
> const sectionRef2 = useRef <HTMLDivElement >(null)
> const sectionRef3 = useRef <HTMLDivElement>(null)
> 
> const sections= [sectionRef1, sectionRef2, sectionRef3]
> 
> 
> function handleScroll(e: Event) {
>     e.preventDefault();
> }
> const scrolling: Scrolling = {
>     enabled: true,
>     events: "scroll,wheel,touchmove,pointermove".split(","),
>     prevent: (e: Event ) => e.preventDefault(),
>     disable() {
>     if (scrolling.enabled) {
>         scrolling.enabled = false;
>         window.addEventListener("scroll", gsap.ticker.tick, {passive: true});
>         scrolling.events.forEach((e, i) => (i ? document : window).addEventListener(e, handleScroll, {passive: false}));
>     }
>     },
>     enable() {
>     if (!scrolling.enabled) {
>         scrolling.enabled = true;
>         window.removeEventListener("scroll", gsap.ticker.tick);
>         scrolling.events.forEach((e, i) => (i ? document : window).removeEventListener(e, handleScroll));
>     }
>     }
> };
> 
> function goToSection(section :any) {
>     if (scrolling.enabled) { 
>     scrolling.disable();
>     gsap.to(window, {
>         scrollTo: {y: section, autoKill: false},
>         onComplete: scrolling.enable,
>         duration: 1
>     });
> } 
> }
> useLayoutEffect(() => {
>     sections.forEach((section, i) => {
>     ScrollTrigger.create({
>         trigger: section.current,
>         start: "top bottom-=1",
>         end: "bottom top+=1",
>         onEnter: () => {goToSection(section.current),changeNumber(i),console.log(i);
>         },
>         onEnterBack: () => {goToSection(section.current),changeNumber(i),console.log(i);
>         }
>     });
>     })
> },[])  
> 
> 
> return(
>     <div className='flex flex-col items-center '>
> 
>     <div ref={sectionRef1} className=' text-white w-screen h-screen mx-auto'>
>       <section>
>         <h1 className=' text-black'> hi first box</h1>
>       </section>
>     </div>
>     <div ref={sectionRef2} className='   w-screen h-screen mx-auto'>
>       <section>
>         <h1>  second box</h1>
>       </section>
>     </div>
>     <div ref={sectionRef3} className='  w-screen h-screen mx-auto'>
>       <section>
>         <h1>  third box</h1>
>       </section>
>     </div>
> 
>   </div>
> )
> ```
> 
> }`



> Hi @TimeLightCurve can you please specifically share the part of code where you are implementing GSAP scroll trigger to create particle transition?

**Comment by VedantSG123** [comment]
@TimeLightCurve , thanks  for sharing the code, I think you are trying to animate the mesh outside the parent component of R3f Points Fx. I would suggest you to also share also the part where you have imported and used R3f Points Fx, then you need to define your GSAP animations there. Share that part, I will then suggest code changes there.

**Comment by TimeLightCurve** [comment]
> @TimeLightCurve , thanks for sharing the code, I think you are trying to animate the mesh outside the parent component of R3f Points Fx. I would suggest you to also share also the part where you have imported and used R3f Points Fx, then you need to define your GSAP animations there. Share that part, I will then suggest code changes there.

tnx for your response, I actually defined a state of current in top of the project so whenever the current changes there is a useEffect hook inside the scene component that runs change Model.

here is the code of scene component:

```
function Scene({ current }: properties) {
  const logo = useGLTF("logo.glb") as logoResult;
  // const logo2 = useGLTF("logo2.glb") as logo2Result;
  const suzanne = useGLTF("suzanne.glb") as SuzanneResult;
  const amongus = useGLTF("among_us.glb") as AmongusResult;
  const dna = useGLTF("dna.glb") as DnaResult;
  const tree = useGLTF("tree.glb") as TreeResult;

  const meshes = [
    logo.nodes.logo,
    tree.nodes.Icosphere012,
    dna.nodes.BezierCircle,
    amongus.nodes.crewmate_body,
    suzanne.nodes.Suzanne,
  ];

  const startTime = useRef(0);
  const progress = useRef(0);
  const FBORef = useRef<R3FPointsFXRefType>(null);
  const previousIndex = useRef<number | null>(null);
  const alaki = useRef(0);

  const { duration, curve } = useControls({
    duration: {
      value: 2,
      min: 0,
      max: 9,
      step: 0.1,
    },
    curve: bezier([0.3, 0.8, 0.3, 0.7]),
  });

  const change3DModel = () => {
    startTime.current = 0;
    alaki.current = current;
    FBORef.current?.setModelB(alaki.current);
  };

  useEffect(() => {
    change3DModel();
  }, [current]);

  useFrame((state) => {
    if (startTime.current === 0) {
      startTime.current = state.clock.elapsedTime;
    }

    const elapsed = state.clock.elapsedTime - startTime.current;

    progress.current = curve.evaluate(Math.min(elapsed / duration, 1));
    if (progress.current >= 1) {
      FBORef.current?.setModelA(current);
      previousIndex.current = current;
      const points = FBORef.current?.getPointsMesh();
      points?.updateMorphTargets(current);
    }

    FBORef.current?.updateProgress(progress.current);
    FBORef.current?.updateTime(state.clock.elapsedTime);
  });

  return (
    <>
      <R3FPointsFX
        modelsArray={meshes}
        pointSize={3.0}
        baseColor="#552674"
        modelA={previousIndex.current}
        modelB={current}
        ref={FBORef}
      />
    </>
  );
}

export default Scene;
```

**Comment by VedantSG123** [comment]
@TimeLightCurve do you want the particles to transition based on the scroll progress from one section to another, yes it is possible by just using `updateProgress` and `setModelA/B` methods

**Comment by VedantSG123** [comment]
In current code you are triggering the animation on section change, and these animations are of fixed duration. This can be done as well, in your case the animations are breaking because I think GSAP timelines aren't  set properly.

**Comment by TimeLightCurve** [comment]
ok thanks a lot ill work on it, one last question, how i can add 6 colors to the mesh like the one you added to the earth model? I'm not that experienced with three js just started to learning don't know how to add shaders as you wrote in documentation

**Comment by TimeLightCurve** [comment]
> @TimeLightCurve do you want the particles to transition based on the scroll progress from one section to another, yes it is possible by just using `updateProgress` and `setModelA/B` methods

im exactly doing that, i saw the other issue some guy asked you if he can set progress based on scroll so im trying to do as you said 

```

  useEffect(() => {
    if (FBORef.current) {
      const ctx = gsap.context(() => {
        const timeline1 = gsap.timeline({
          scrollTrigger: {
            trigger: sections[0],
            scroller: "#main",
            start: "bottom bottom-=100px",
            end: "bottom top+=100px",
            scrub: 1,
            onUpdate: (self) => {
              FBORef.current?.updateProgress(self.progress)
            },
            onEnter: () => {
              FBORef.current?.setModelB(1)
            },
            onLeave: () => {
              FBORef.current?.setModelA(1)
            },
            onEnterBack: () => {
              FBORef.current?.setModelA(0)
            },
            onLeaveBack: () => {
              FBORef.current?.setModelB(0)
            },
          },
        })
      })
      return () => ctx.revert()
    }
  }, [])
 
```

this part of the code you mentioned it should be inside the useFrame right?

**Comment by VedantSG123** [comment]
@TimeLightCurve yes it is indeed the part of code where we are updating the progress on scroll, but it should not to be called inside `useFrame`, as the scroll progress variable from `GSAP` is the one getting updated due to scroll and we are passing that reactive value inside the `updateProgress` every time scroll position updates. 

Following code might assist you (it is in jsx but I think you can implement the same in typescript):
```jsx


import { R3FPointsFX } from "r3f-points-fx"
import { useFrame } from "@react-three/fiber"
import GSAP from "gsap"
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"


GSAP.registerPlugin(ScrollTrigger)
function Morph() {


  const meshes = [/*----------pass your meshes inside mesh array here-----------**/]

//select your sections directly from the document body
  const section1 = document.getElementById("animate-1")


  const morphRef = useRef()



  //particles transition timelines
  //transition from model 0 to model 1 and also transition back on reverse scroll
  useEffect(() => {
    if (morphRef.current && section1) {
      const ctx = GSAP.context(() => {
        const timeline1 = GSAP.timeline({
          scrollTrigger: {
            trigger: section1,
            scroller: "#main", //I have used this container for scroller, by default scroller is document body
            start: "bottom bottom-=100px",
            end: "bottom top+=100px",
            scrub: 1,
            onUpdate: (self) => {
              morphRef.current.updateProgress(self.progress)
            },
            onEnter: () => {
              morphRef.current.setModelB(1)
            },
            onLeave: () => {
              morphRef.current.setModelA(1)
            },
            onEnterBack: () => {
              morphRef.current.setModelA(0)
            },
            onLeaveBack: () => {
              morphRef.current.setModelB(0)
            },
          },
        })
      })
      return () => ctx.revert()
    }
  }, [])

//used useFrame only to update the local clock of the R3fPointsFX
  useFrame((state, delta) => {
    if (morphRef.current && rotateMesh.current === true) {
      morphRef.current.updateTime(state.clock.elapsedTime)
      const mesh = morphRef.current.getPointsMesh()
      mesh.rotation.y = state.clock.elapsedTime * 0.1
    }
    if (morphRef.current) {
      morphRef.current.updateTime(state.clock.elapsedTime)
    }
  })

  return (
    <>
      
          <R3FPointsFX
            modelsArray={meshes}
            baseColor="#ff0000"
            modelA={0}
            modelB={0}
            ref={morphRef}
            scale={[1.7, 1.7, 1.7]}
            pointSize={10}
            pointsCount={100}
            alpha={1.2}
          />
      
    </>
  )
}


export default Morph
```

**Comment by TimeLightCurve** [comment]
thank you bro it's working now I appreciate the time you spent on solving my problem. 

one last question, how I can add 6 colors to the mesh like the one you added to the earth model? I'm not that experienced with three js just started to learning don't know how to add shaders as you wrote in the documentation

**Comment by VedantSG123** [comment]
Please raise a separate issue for this, just trying to organise stuff 😅
