### ISSUE TITLE
Doesn't work with the latest threejs: three@0.166.1

### ISSUE THREAD

**Issue by syntralis** [VedantSG123/R3FPointsFX#8]
Firstly thanks for this library.

My problem is I'm running: `npm i r3f-points-fx`

The output is:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: futuristic@0.0.0
npm ERR! Found: three@0.166.1
npm ERR! node_modules/three
npm ERR!   three@"^0.166.1" from the root project
npm ERR!   peer three@">=0.133" from @react-three/fiber@8.16.8
npm ERR!   node_modules/@react-three/fiber
npm ERR!     @react-three/fiber@"^8.16.8" from the root project
npm ERR!     peer @react-three/fiber@"^8.14.5" from r3f-points-fx@1.0.5
npm ERR!     node_modules/r3f-points-fx
npm ERR!       r3f-points-fx@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer three@"^0.157.0" from r3f-points-fx@1.0.5
npm ERR! node_modules/r3f-points-fx
npm ERR!   r3f-points-fx@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Installed it using --legacy-peer-deps, but resulted in an error in the console and the page not loading at all.
Thanks again.

**Comment by syntralis** [comment]
I just had to clone the repository and pick the code myself as a component, it's working great !
Thank you for sharing.

**Comment by VedantSG123** [comment]
> I just had to clone the repository and pick the code myself as a component, it's working great ! Thank you for sharing.

Thanks for trying it out, yes had newer versions of peer dependencies, for what standard is followed don't know. Sorry for late reply, didn't got to see this issue before
